steps:
  - id: 'prepare-secret'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --project=${_PROJECT_ID} --secret=${_ENV}-${_SECRET_NAME} --format='get(payload.data)' | tr '_-' '/+' | base64 -d > ${_DECRYPTED_ENV_FILE_LOCATION}
  - id: 'build-app-image'
    name: 'gcr.io/kaniko-project/executor:latest'
    waitFor: ['prepare-secret']
    args:
      - --dockerfile=${_APP_DOCKER_FILE}
      - --destination=gcr.io/${_PROJECT_ID}/${_CLOUD_RUN_SERVICE_NAME}:latest
      - --destination=gcr.io/${_PROJECT_ID}/${_CLOUD_RUN_SERVICE_NAME}:$TAG_NAME
      - --cache=true
      - --cache-ttl=336h
  - id: 'deploy-app'
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['build-app-image']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_CLOUD_RUN_SERVICE_NAME} \
          --image gcr.io/$_PROJECT_ID/${_CLOUD_RUN_SERVICE_NAME}:latest \
          --allow-unauthenticated \
          --region asia-northeast1 \
          --platform managed \
substitutions:
  _ENV: staging
  _SECRET_NAME: vue3-nuxt3-conventions
  _PROJECT_ID: azoom-n-d-phong
  _DECRYPTED_ENV_FILE_LOCATION: ./.env
  _APP_DOCKER_FILE: ./deployment/Dockerfile
  _CLOUD_RUN_SERVICE_NAME: vue3-nuxt3-conventions
timeout: 900s
